[package]
name = "kikid"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "kiki file manager daemon"

[[bin]]
name = "kikid"
path = "src/main.rs"

[dependencies]
libc = "0.2"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "gif", "webp", "bmp", "tiff"] }
png = "0.17"

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { version = "0.38", features = ["fs", "net", "process", "std"] }
